### ISSUE TITLE
Segfault on Windows 8 running test suite

### ISSUE THREAD

**Issue by djberg96** [djberg96/win32-xpath#1]
Windows 8
ruby 2.1.6p336 (2015-04-13 revision 50298) [i386-mingw32] with Devkit

Of possible note: username is djberge, but home dir is C:\Users\Daniel

```
PS C:\Users\Daniel\Repositories\win32-xpath> rake
Temporarily enhancing PATH to include DevKit...
C:/Ruby21/bin/ruby.exe extconf.rb
checking for main() in -lshlwapi... yes
checking for main() in -ladvapi32... yes
creating Makefile
make
generating xpath-i386-mingw32.def
compiling win32/xpath.c
win32/xpath.c: In function 'find_user':
win32/xpath.c:59:3: warning: passing argument 2 of 'swprintf' makes pointer from integer without a cast [enabled by defa
ult]
In file included from c:/Ruby21/include/ruby-2.1.0/ruby/defines.h:26:0,
                 from c:/Ruby21/include/ruby-2.1.0/ruby/ruby.h:29,
                 from c:/Ruby21/include/ruby-2.1.0/ruby.h:33,
                 from win32/xpath.c:1:
c:\devkit\mingw\bin\../lib/gcc/i686-w64-mingw32/4.7.2/../../../../i686-w64-mingw32/include/stdio.h:705:23: note: expecte
d 'const wchar_t * __restrict__' but argument is of type 'int'
win32/xpath.c:82:5: warning: passing argument 2 of 'swprintf' makes pointer from integer without a cast [enabled by defa
ult]
In file included from c:/Ruby21/include/ruby-2.1.0/ruby/defines.h:26:0,
                 from c:/Ruby21/include/ruby-2.1.0/ruby/ruby.h:29,
                 from c:/Ruby21/include/ruby-2.1.0/ruby.h:33,
                 from win32/xpath.c:1:
c:\devkit\mingw\bin\../lib/gcc/i686-w64-mingw32/4.7.2/../../../../i686-w64-mingw32/include/stdio.h:705:23: note: expecte
d 'const wchar_t * __restrict__' but argument is of type 'unsigned int'
win32/xpath.c: In function 'expand_tilde':
win32/xpath.c:108:21: warning: initialization discards 'const' qualifier from pointer target type [enabled by default]
linking shared-object win32/xpath.so
cp xpath.so win32
Loaded suite C:/Ruby21/lib/ruby/2.1.0/rake/rake_test_loader
Started
..............C:/Users/Daniel/Repositories/win32-xpath/test/test_win32_xpath.rb:142: [BUG] Segmentation fault
ruby 2.1.6p336 (2015-04-13 revision 50298) [i386-mingw32]

-- Control frame information -----------------------------------------------
c:0021 p:---- s:0099 e:000098 CFUNC  :expand_path
c:0020 p:0028 s:0095 e:000092 LAMBDA C:/Users/Daniel/Repositories/win32-xpath/test/test_win32_xpath.rb:142 [FINISH]
c:0019 p:0079 s:0091 e:000090 METHOD C:/Ruby21/lib/ruby/gems/2.1.0/gems/test-unit-3.1.2/lib/test/unit/testcase.rb:718
c:0018 p:0062 s:0087 e:000086 METHOD C:/Ruby21/lib/ruby/gems/2.1.0/gems/test-unit-3.1.2/lib/test/unit/testcase.rb:458
c:0017 p:0027 s:0083 e:000082 METHOD C:/Ruby21/lib/ruby/gems/2.1.0/gems/test-unit-3.1.2/lib/test/unit/testsuite.rb:124
c:0016 p:0085 s:0075 e:000074 METHOD C:/Ruby21/lib/ruby/gems/2.1.0/gems/test-unit-3.1.2/lib/test/unit/testsuite.rb:53
c:0015 p:0027 s:0069 E:000e80 METHOD C:/Ruby21/lib/ruby/gems/2.1.0/gems/test-unit-3.1.2/lib/test/unit/testsuite.rb:124
c:0014 p:0085 s:0061 e:000060 METHOD C:/Ruby21/lib/ruby/gems/2.1.0/gems/test-unit-3.1.2/lib/test/unit/testsuite.rb:53
c:0013 p:0029 s:0055 E:001050 METHOD C:/Ruby21/lib/ruby/gems/2.1.0/gems/test-unit-3.1.2/lib/test/unit/ui/testrunnermedia
tor.rb:65
c:0012 p:0042 s:0051 e:000050 BLOCK  C:/Ruby21/lib/ruby/gems/2.1.0/gems/test-unit-3.1.2/lib/test/unit/ui/testrunnermedia
tor.rb:44
c:0011 p:0076 s:0049 E:001088 METHOD C:/Ruby21/lib/ruby/gems/2.1.0/gems/test-unit-3.1.2/lib/test/unit/ui/testrunnermedia
tor.rb:100
c:0010 p:0059 s:0041 E:000e38 METHOD C:/Ruby21/lib/ruby/gems/2.1.0/gems/test-unit-3.1.2/lib/test/unit/ui/testrunnermedia
tor.rb:40
c:0009 p:0009 s:0035 e:000034 METHOD C:/Ruby21/lib/ruby/gems/2.1.0/gems/test-unit-3.1.2/lib/test/unit/ui/testrunner.rb:4
0
c:0008 p:0025 s:0032 e:000031 METHOD C:/Ruby21/lib/ruby/gems/2.1.0/gems/test-unit-3.1.2/lib/test/unit/ui/testrunner.rb:2
5
c:0007 p:0017 s:0029 e:000028 METHOD C:/Ruby21/lib/ruby/gems/2.1.0/gems/test-unit-3.1.2/lib/test/unit/ui/testrunnerutili
ties.rb:24
c:0006 p:0013 s:0024 e:000023 BLOCK  C:/Ruby21/lib/ruby/gems/2.1.0/gems/test-unit-3.1.2/lib/test/unit/autorunner.rb:411
c:0005 p:0031 s:0022 e:000021 METHOD C:/Ruby21/lib/ruby/gems/2.1.0/gems/test-unit-3.1.2/lib/test/unit/autorunner.rb:467
c:0004 p:0146 s:0018 E:001a64 METHOD C:/Ruby21/lib/ruby/gems/2.1.0/gems/test-unit-3.1.2/lib/test/unit/autorunner.rb:410
c:0003 p:0067 s:0013 e:000012 METHOD C:/Ruby21/lib/ruby/gems/2.1.0/gems/test-unit-3.1.2/lib/test/unit/autorunner.rb:59
c:0002 p:0041 s:0005 e:000003 BLOCK  C:/Ruby21/lib/ruby/gems/2.1.0/gems/test-unit-3.1.2/lib/test/unit.rb:502 [FINISH]
c:0001 p:0000 s:0002 E:000ffc TOP    [FINISH]

C:/Ruby21/lib/ruby/gems/2.1.0/gems/test-unit-3.1.2/lib/test/unit.rb:502:in `block (2 levels) in <top (required)>'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/test-unit-3.1.2/lib/test/unit/autorunner.rb:59:in `run'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/test-unit-3.1.2/lib/test/unit/autorunner.rb:410:in `run'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/test-unit-3.1.2/lib/test/unit/autorunner.rb:467:in `change_work_directory'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/test-unit-3.1.2/lib/test/unit/autorunner.rb:411:in `block in run'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/test-unit-3.1.2/lib/test/unit/ui/testrunnerutilities.rb:24:in `run'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/test-unit-3.1.2/lib/test/unit/ui/testrunner.rb:25:in `start'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/test-unit-3.1.2/lib/test/unit/ui/testrunner.rb:40:in `start_mediator'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/test-unit-3.1.2/lib/test/unit/ui/testrunnermediator.rb:40:in `run'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/test-unit-3.1.2/lib/test/unit/ui/testrunnermediator.rb:100:in `with_listener'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/test-unit-3.1.2/lib/test/unit/ui/testrunnermediator.rb:44:in `block in run'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/test-unit-3.1.2/lib/test/unit/ui/testrunnermediator.rb:65:in `run_suite'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/test-unit-3.1.2/lib/test/unit/testsuite.rb:53:in `run'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/test-unit-3.1.2/lib/test/unit/testsuite.rb:124:in `run_test'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/test-unit-3.1.2/lib/test/unit/testsuite.rb:53:in `run'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/test-unit-3.1.2/lib/test/unit/testsuite.rb:124:in `run_test'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/test-unit-3.1.2/lib/test/unit/testcase.rb:458:in `run'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/test-unit-3.1.2/lib/test/unit/testcase.rb:718:in `run_test'
C:/Users/Daniel/Repositories/win32-xpath/test/test_win32_xpath.rb:142:in `block in <class:Test_XPath>'
C:/Users/Daniel/Repositories/win32-xpath/test/test_win32_xpath.rb:142:in `expand_path'

-- C level backtrace information -------------------------------------------
C:\Windows\SYSTEM32\ntdll.dll(ZwWaitForSingleObject+0xc) [0x76EDDA1C]
C:\Windows\SYSTEM32\KERNELBASE.dll(WaitForSingleObject+0x12) [0x74C910B4]
C:\Ruby21\bin\msvcrt-ruby210.dll(rb_vm_bugreport+0xa7) [0x6D388C07]
C:\Ruby21\bin\msvcrt-ruby210.dll(rb_name_err_mesg_new+0x69f) [0x6D24440F]
C:\Ruby21\bin\msvcrt-ruby210.dll(rb_bug+0x2e) [0x6D2451BE]
C:\Ruby21\bin\msvcrt-ruby210.dll(rb_check_safe_str+0x33b) [0x6D30AFFB]
 [0x00401866]
C:\Windows\SYSTEM32\ntdll.dll(RtlCreateUserThread+0x95fa) [0x76F2BE94]

-- Other runtime information -----------------------------------------------

* Loaded script: C:/Ruby21/lib/ruby/2.1.0/rake/rake_test_loader.rb

* Loaded features:

    0 enumerator.so
    1 C:/Ruby21/lib/ruby/2.1.0/i386-mingw32/enc/encdb.so
    2 C:/Ruby21/lib/ruby/2.1.0/i386-mingw32/enc/iso_8859_1.so
    3 C:/Ruby21/lib/ruby/2.1.0/i386-mingw32/enc/trans/transdb.so
    4 C:/Ruby21/lib/ruby/2.1.0/i386-mingw32/rbconfig.rb
    5 C:/Ruby21/lib/ruby/2.1.0/rubygems/compatibility.rb
    6 C:/Ruby21/lib/ruby/2.1.0/rubygems/defaults.rb
    7 C:/Ruby21/lib/ruby/2.1.0/rubygems/deprecate.rb
    8 C:/Ruby21/lib/ruby/2.1.0/rubygems/errors.rb
    9 C:/Ruby21/lib/ruby/2.1.0/rubygems/version.rb
   10 C:/Ruby21/lib/ruby/2.1.0/rubygems/requirement.rb
   11 C:/Ruby21/lib/ruby/2.1.0/rubygems/platform.rb
   12 C:/Ruby21/lib/ruby/2.1.0/rubygems/basic_specification.rb
   13 C:/Ruby21/lib/ruby/2.1.0/rubygems/stub_specification.rb
   14 C:/Ruby21/lib/ruby/2.1.0/rubygems/util/stringio.rb
   15 C:/Ruby21/lib/ruby/2.1.0/rubygems/specification.rb
   16 C:/Ruby21/lib/ruby/2.1.0/rubygems/exceptions.rb
   17 C:/Ruby21/lib/ruby/2.1.0/rubygems/defaults/operating_system.rb
   18 C:/Ruby21/lib/ruby/2.1.0/rubygems/core_ext/kernel_gem.rb
   19 thread.rb
   20 C:/Ruby21/lib/ruby/2.1.0/i386-mingw32/thread.so
   21 C:/Ruby21/lib/ruby/2.1.0/monitor.rb
   22 C:/Ruby21/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb
   23 C:/Ruby21/lib/ruby/2.1.0/rubygems.rb
   24 C:/Ruby21/lib/ruby/2.1.0/rubygems/dependency.rb
   25 C:/Ruby21/lib/ruby/2.1.0/rubygems/path_support.rb
   26 C:/Ruby21/lib/ruby/2.1.0/rake/version.rb
   27 C:/Ruby21/lib/ruby/2.1.0/i386-mingw32/etc.so
   28 C:/Ruby21/lib/ruby/2.1.0/fileutils.rb
   29 C:/Ruby21/lib/ruby/2.1.0/singleton.rb
   30 C:/Ruby21/lib/ruby/2.1.0/optparse.rb
   31 C:/Ruby21/lib/ruby/2.1.0/ostruct.rb
   32 C:/Ruby21/lib/ruby/2.1.0/rake/ext/module.rb
   33 C:/Ruby21/lib/ruby/2.1.0/rake/ext/core.rb
   34 C:/Ruby21/lib/ruby/2.1.0/rake/ext/string.rb
   35 C:/Ruby21/lib/ruby/2.1.0/rake/early_time.rb
   36 C:/Ruby21/lib/ruby/2.1.0/rake/ext/time.rb
   37 C:/Ruby21/lib/ruby/2.1.0/rake/alt_system.rb
   38 C:/Ruby21/lib/ruby/2.1.0/rake/win32.rb
   39 C:/Ruby21/lib/ruby/2.1.0/rake/linked_list.rb
   40 C:/Ruby21/lib/ruby/2.1.0/rake/scope.rb
   41 C:/Ruby21/lib/ruby/2.1.0/rake/task_argument_error.rb
   42 C:/Ruby21/lib/ruby/2.1.0/rake/rule_recursion_overflow_error.rb
   43 C:/Ruby21/lib/ruby/2.1.0/shellwords.rb
   44 C:/Ruby21/lib/ruby/2.1.0/rake/task_manager.rb
   45 C:/Ruby21/lib/ruby/2.1.0/rake/cloneable.rb
   46 C:/Ruby21/lib/ruby/2.1.0/rake/file_utils.rb
   47 C:/Ruby21/lib/ruby/2.1.0/rake/file_utils_ext.rb
   48 C:/Ruby21/lib/ruby/2.1.0/rake/pathmap.rb
   49 C:/Ruby21/lib/ruby/2.1.0/rake/file_list.rb
   50 C:/Ruby21/lib/ruby/2.1.0/set.rb
   51 C:/Ruby21/lib/ruby/2.1.0/rake/promise.rb
   52 C:/Ruby21/lib/ruby/2.1.0/rake/thread_pool.rb
   53 C:/Ruby21/lib/ruby/2.1.0/rake/private_reader.rb
   54 C:/Ruby21/lib/ruby/2.1.0/rake/thread_history_display.rb
   55 C:/Ruby21/lib/ruby/2.1.0/rake/trace_output.rb
   56 C:/Ruby21/lib/ruby/2.1.0/rake/application.rb
   57 C:/Ruby21/lib/ruby/2.1.0/rake/rake_module.rb
   58 C:/Ruby21/lib/ruby/2.1.0/rake/pseudo_status.rb
   59 C:/Ruby21/lib/ruby/2.1.0/rake/task_arguments.rb
   60 C:/Ruby21/lib/ruby/2.1.0/rake/invocation_chain.rb
   61 C:/Ruby21/lib/ruby/2.1.0/rake/invocation_exception_mixin.rb
   62 C:/Ruby21/lib/ruby/2.1.0/rake/task.rb
   63 C:/Ruby21/lib/ruby/2.1.0/rake/file_task.rb
   64 C:/Ruby21/lib/ruby/2.1.0/rake/file_creation_task.rb
   65 C:/Ruby21/lib/ruby/2.1.0/rake/multi_task.rb
   66 C:/Ruby21/lib/ruby/2.1.0/rake/dsl_definition.rb
   67 C:/Ruby21/lib/ruby/2.1.0/rake/default_loader.rb
   68 C:/Ruby21/lib/ruby/2.1.0/rake/name_space.rb
   69 C:/Ruby21/lib/ruby/2.1.0/rake/backtrace.rb
   70 C:/Ruby21/lib/ruby/2.1.0/rake.rb
   71 C:/Ruby21/lib/ruby/gems/2.1.0/gems/test-unit-3.1.2/lib/test-unit.rb
   72 C:/Ruby21/lib/ruby/2.1.0/tmpdir.rb
   73 C:/Users/Daniel/Repositories/win32-xpath/ext/win32/xpath.so
   74 C:/Ruby21/lib/ruby/gems/2.1.0/gems/test-unit-3.1.2/lib/test/unit/attribute.rb
   75 C:/Ruby21/lib/ruby/gems/2.1.0/gems/test-unit-3.1.2/lib/test/unit/fixture.rb
   76 C:/Ruby21/lib/ruby/gems/2.1.0/gems/test-unit-3.1.2/lib/test/unit/exception-handler.rb
   77 C:/Ruby21/lib/ruby/gems/2.1.0/gems/test-unit-3.1.2/lib/test/unit/assertion-failed-error.rb
   78 C:/Ruby21/lib/ruby/gems/2.1.0/gems/test-unit-3.1.2/lib/test/unit/util/backtracefilter.rb
   79 C:/Ruby21/lib/ruby/gems/2.1.0/gems/test-unit-3.1.2/lib/test/unit/util/method-owner-finder.rb
   80 C:/Ruby21/lib/ruby/gems/2.1.0/gems/test-unit-3.1.2/lib/test/unit/diff.rb
   81 C:/Ruby21/lib/ruby/gems/2.1.0/gems/power_assert-0.2.3/lib/power_assert/version.rb
   82 C:/Ruby21/lib/ruby/gems/2.1.0/gems/power_assert-0.2.3/lib/power_assert/enable_tracepoint_events.rb
   83 C:/Ruby21/lib/ruby/2.1.0/i386-mingw32/ripper.so
   84 C:/Ruby21/lib/ruby/2.1.0/ripper/core.rb
   85 C:/Ruby21/lib/ruby/2.1.0/ripper/lexer.rb
   86 C:/Ruby21/lib/ruby/2.1.0/ripper/filter.rb
   87 C:/Ruby21/lib/ruby/2.1.0/ripper/sexp.rb
   88 C:/Ruby21/lib/ruby/2.1.0/ripper.rb
   89 C:/Ruby21/lib/ruby/gems/2.1.0/gems/power_assert-0.2.3/lib/power_assert.rb
   90 C:/Ruby21/lib/ruby/gems/2.1.0/gems/test-unit-3.1.2/lib/test/unit/assertions.rb
   91 C:/Ruby21/lib/ruby/gems/2.1.0/gems/test-unit-3.1.2/lib/test/unit/failure.rb
   92 C:/Ruby21/lib/ruby/gems/2.1.0/gems/test-unit-3.1.2/lib/test/unit/error.rb
   93 C:/Ruby21/lib/ruby/gems/2.1.0/gems/test-unit-3.1.2/lib/test/unit/pending.rb
   94 C:/Ruby21/lib/ruby/gems/2.1.0/gems/test-unit-3.1.2/lib/test/unit/omission.rb
   95 C:/Ruby21/lib/ruby/gems/2.1.0/gems/test-unit-3.1.2/lib/test/unit/notification.rb
   96 C:/Ruby21/lib/ruby/gems/2.1.0/gems/test-unit-3.1.2/lib/test/unit/priority.rb
   97 C:/Ruby21/lib/ruby/gems/2.1.0/gems/test-unit-3.1.2/lib/test/unit/data.rb
   98 C:/Ruby21/lib/ruby/gems/2.1.0/gems/test-unit-3.1.2/lib/test/unit/testsuite.rb
   99 C:/Ruby21/lib/ruby/gems/2.1.0/gems/test-unit-3.1.2/lib/test/unit/test-suite-creator.rb
  100 C:/Ruby21/lib/ruby/gems/2.1.0/gems/test-unit-3.1.2/lib/test/unit/util/output.rb
  101 C:/Ruby21/lib/ruby/gems/2.1.0/gems/test-unit-3.1.2/lib/test/unit/testcase.rb
  102 C:/Ruby21/lib/ruby/gems/2.1.0/gems/test-unit-3.1.2/lib/test/unit/color.rb
  103 C:/Ruby21/lib/ruby/gems/2.1.0/gems/test-unit-3.1.2/lib/test/unit/color-scheme.rb
  104 C:/Ruby21/lib/ruby/gems/2.1.0/gems/test-unit-3.1.2/lib/test/unit/attribute-matcher.rb
  105 C:/Ruby21/lib/ruby/gems/2.1.0/gems/test-unit-3.1.2/lib/test/unit/runner/console.rb
  106 C:/Ruby21/lib/ruby/gems/2.1.0/gems/test-unit-3.1.2/lib/test/unit/runner/emacs.rb
  107 C:/Ruby21/lib/ruby/gems/2.1.0/gems/test-unit-3.1.2/lib/test/unit/runner/xml.rb
  108 C:/Ruby21/lib/ruby/gems/2.1.0/gems/test-unit-3.1.2/lib/test/unit/autorunner.rb
  109 C:/Ruby21/lib/ruby/gems/2.1.0/gems/test-unit-3.1.2/lib/test/unit.rb
  110 C:/Users/Daniel/Repositories/win32-xpath/test/test_win32_xpath.rb
  111 C:/Ruby21/lib/ruby/gems/2.1.0/gems/test-unit-3.1.2/lib/test/unit/ui/console/outputlevel.rb
  112 C:/Ruby21/lib/ruby/gems/2.1.0/gems/test-unit-3.1.2/lib/test/unit/collector.rb
  113 C:/Ruby21/lib/ruby/gems/2.1.0/gems/test-unit-3.1.2/lib/test/unit/collector/descendant.rb
  114 C:/Ruby21/lib/ruby/2.1.0/i386-mingw32/io/console.so
  115 C:/Ruby21/lib/ruby/gems/2.1.0/gems/test-unit-3.1.2/lib/test/unit/code-snippet-fetcher.rb
  116 C:/Ruby21/lib/ruby/2.1.0/English.rb
  117 C:/Ruby21/lib/ruby/gems/2.1.0/gems/test-unit-3.1.2/lib/test/unit/fault-location-detector.rb
  118 C:/Ruby21/lib/ruby/gems/2.1.0/gems/test-unit-3.1.2/lib/test/unit/ui/testrunnerutilities.rb
  119 C:/Ruby21/lib/ruby/gems/2.1.0/gems/test-unit-3.1.2/lib/test/unit/ui/testrunner.rb
  120 C:/Ruby21/lib/ruby/gems/2.1.0/gems/test-unit-3.1.2/lib/test/unit/util/procwrapper.rb
  121 C:/Ruby21/lib/ruby/gems/2.1.0/gems/test-unit-3.1.2/lib/test/unit/util/observable.rb
  122 C:/Ruby21/lib/ruby/gems/2.1.0/gems/test-unit-3.1.2/lib/test/unit/testresult.rb
  123 C:/Ruby21/lib/ruby/gems/2.1.0/gems/test-unit-3.1.2/lib/test/unit/ui/testrunnermediator.rb
  124 C:/Ruby21/lib/ruby/gems/2.1.0/gems/test-unit-3.1.2/lib/test/unit/ui/console/testrunner.rb
  125 C:/Ruby21/lib/ruby/2.1.0/i386-mingw32/enc/trans/single_byte.so

[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
For details: http://www.ruby-lang.org/bugreport.html


This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
rake aborted!
Command failed with status (3): [ruby -I"lib;ext" -I"C:/Ruby21/lib/ruby/2.1.0" "C:/Ruby21/lib/ruby/2.1.0/rake/rake_test_
loader.rb" "test/test_win32_xpath.rb" ]

Tasks: TOP => default => test
(See full trace by running task with --trace)
```

**Comment by djberg96** [comment]
Actually, I'm seeing this on Windows 7 too where my login and path match, too, so I don't think that's the issue. I guess I always compiled with VS.

**Comment by djberg96** [comment]
I think this is the line that's choking:

https://github.com/djberg96/win32-xpath/blob/master/ext/win32/xpath.c#L59

**Comment by djberg96** [comment]
Looks like there's different versions of swprintf for historical reasons:

http://mingw-users.1079350.n2.nabble.com/Compilation-problem-with-swprintf-td5195629.html

I think this does it:

#ifdef __MINGW32__
#define swprintf _snwprintf 
#endif
